openapi: 3.1.0
x-stoplight:
  id: iwgwivirp0a05
info:
  title: Decision Support API (HR-Open)
  license:
    name: Unknown
    url: 'https://nayya.com'
  version: '1.0'
  x-logo:
    url: /docs/nayya-blue.png
    backgroundColor: '#FFFFFF'
    altText: Nayya
  description: HrOpen Decision Support API
  contact:
    email: api@nayya.com
    url: 'https://nayya.com'
    name: Nayya Team
  termsOfService: 'https://nayya.com'
  summary: Decission Support in Hr Open
servers:
  - url: 'https://app.nayya.com'
    description: Production
  - url: 'https://staging.app.nayya.com'
    description: Staging
  - url: 'https://qa.app.nayya.com'
    description: QA
  - url: 'http://localhost:3000'
    description: Development
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: JWT token
  headers:
    Request-Id:
      description: Unique id of request
      schema:
        type: string
      example: 123e4567-e89b-12d3-a456-426614174000
  schemas:
    ApiError409Response:
      title: ApiError409Response
      x-stoplight:
        id: p0wj99p3y33n2
      type: object
      examples:
        - status: 409
          message: A carrier is required to create plan
      properties:
        status:
          type: number
          minimum: 409
          maximum: 409
        message:
          type: string
        errors:
          type: object
      required:
        - status
        - message
      x-tags:
        - common
    ApiError422Response:
      title: ApiError422Response
      x-stoplight:
        id: vop9jpjt6piox
      type: object
      examples:
        - status: 422
          message: Invalid request
          errors:
            age: Age must greater than 0
      properties:
        status:
          type: number
          minimum: 422
          maximum: 422
        message:
          type: string
        errors:
          type: object
      required:
        - status
        - message
        - errors
      x-tags:
        - common
    EmployerCreateParams:
      title: EmployerCreateParams
      x-stoplight:
        id: 2ope53bmwsihp
      type: object
      properties:
        employerOrganization:
          allOf:
            - $ref: '#/components/schemas/EntityType'
            - type: object
              properties:
                taxId:
                  $ref: '#/components/schemas/IdentifierType'
      examples:
        - id:
            value: string
          name: string
      x-tags:
        - hropen
    EmployerCreateResponse:
      title: EmployerCreateResponse
      x-stoplight:
        id: obofsagyawn5a
      examples:
        - id:
            value: string
          name: string
      allOf:
        - $ref: '#/components/schemas/EntityType'
        - type: object
          properties:
            taxId:
              $ref: '#/components/schemas/IdentifierType'
      x-tags:
        - hropen
    EmployerRetrieveResponse:
      title: EmployerRetrieveResponse
      x-stoplight:
        id: iit1d7gvu4usl
      examples:
        - id:
            value: string
          name: string
      allOf:
        - $ref: '#/components/schemas/EntityType'
        - type: object
          properties:
            taxId:
              $ref: '#/components/schemas/IdentifierType'
      x-tags:
        - hropen
    EntityType:
      title: EntityType
      x-stoplight:
        id: 96i3sqnafzuz4
      type: object
      description: 'A description of an entity with id, name and code.'
      properties:
        id:
          $ref: '#/components/schemas/IdentifierType'
        name:
          type: string
          description: Free text description for that entity.
      required:
        - id
        - name
      examples:
        - id:
            value: string
          name: string
      x-tags:
        - hropen/base
    IdentifierType:
      title: IdentityType
      x-stoplight:
        id: h55gfh6ql05c0
      type: object
      properties:
        value:
          type: string
          description: The identitifier
      required:
        - value
      examples:
        - value: string
      x-tags:
        - hropen/base
paths:
  /hr_open/employers:
    post:
      summary: Add an employer
      tags:
        - Employers
      operationId: post-employer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    schema:
                      $ref: '#/components/schemas/EmployerCreateResponse'
              examples:
                '201':
                  value:
                    id:
                      value: string
                    name: string
                    taxId:
                      value: string
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError409Response'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError422Response'
      description: Add an employer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployerCreateParams'
            examples:
              Simple:
                value:
                  employerOrganization:
                    id:
                      value: string
                    name: string
        description: ''
    parameters: []
  '/hr_open/employers/{employer_id}':
    get:
      summary: Retrieve an employer
      tags:
        - Employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/EmployerRetrieveResponse'
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
      operationId: get-employer
      description: Retrieve an employer.
    parameters:
      - schema:
          type: string
        name: employer_id
        in: path
        required: true
        description: External employer id
  '/hr_open/employers/{employer_id}/employees/{employee_id}':
    parameters:
      - schema:
          type: string
        name: employer_id
        in: path
        required: true
        description: External employer id
      - schema:
          type: string
        name: employee_id
        in: path
        required: true
        description: External employee id
    delete:
      summary: Remove an employee
      tags:
        - Employees
      operationId: delete-employers-employer_id-employees-employee_id
      responses:
        '200':
          description: OK
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError409Response'
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError422Response'
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
      description: Remove an employee and all PII.
tags:
  - name: Employees
    description: Entity for an employee
  - name: Employers
    description: Entity that employees people
security:
  - bearerAuth: []
