openapi: 3.1.0
x-stoplight:
  id: iwgwivirp0a05
info:
  title: Decision Support API (HR-Open)
  license:
    name: Unknown
    url: 'https://nayya.com'
  version: '1.0'
  x-logo:
    url: /docs/nayya-blue.png
    backgroundColor: '#FFFFFF'
    altText: Nayya
  description: HrOpen Decision Support API
  contact:
    email: api@nayya.com
    url: 'https://nayya.com'
    name: Nayya Team
  termsOfService: 'https://nayya.com'
  summary: Decission Support in Hr Open
servers:
  - url: 'https://app.nayya.com'
    description: Production
  - url: 'https://staging.app.nayya.com'
    description: Staging
  - url: 'https://qa.app.nayya.com'
    description: QA
  - url: 'http://localhost:3000'
    description: Development  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: JWT token
  headers:
    Request-Id:
      description: Unique id of request
      schema:
        type: string
      example: 123e4567-e89b-12d3-a456-426614174000
paths:
  /hr_open/employers:
    post:
      summary: Add an employer
      tags:
        - Employers
      operationId: post-employer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    schema:
                      $ref: ../models/hropen/EmployerCreateResponse.yaml
              examples:
                '201':
                  value:
                    id:
                      value: string
                    name: string
                    taxId:
                      value: string
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: ../models/common/ApiError409Response.yaml
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: ../models/common/ApiError422Response.yaml
      description: Add an employer
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/hropen/EmployerCreateParams.yaml
            examples:
              Simple:
                value:
                  employerOrganization:
                    id:
                      value: string
                    name: string
        description: ''
    parameters: []
  '/hr_open/employers/{employer_id}':
    get:
      summary: Retrieve an employer
      tags:
        - Employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: ../models/hropen/EmployerRetrieveResponse.yaml
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
      operationId: get-employer
      description: Retrieve an employer.
    parameters:
      - schema:
          type: string
        name: employer_id
        in: path
        required: true
        description: External employer id
  '/hr_open/employers/{employer_id}/employees/{employee_id}':
    parameters:
      - schema:
          type: string
        name: employer_id
        in: path
        required: true
        description: External employer id
      - schema:
          type: string
        name: employee_id
        in: path
        required: true
        description: External employee id
    delete:
      summary: Remove an employee
      tags:
        - Employees
      operationId: delete-employers-employer_id-employees-employee_id
      responses:
        '200':
          description: OK
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: ../models/common/ApiError409Response.yaml
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: ../models/common/ApiError422Response.yaml
          headers:
            Request-Id:
              $ref: '#/components/headers/Request-Id'
      description: Remove an employee and all PII.
tags:
  - name: Employees
    description: Entity for an employee
  - name: Employers
    description: Entity that employees people
security:
  - bearerAuth: []
